### ISSUE TITLE
makemigrations not working

### ISSUE THREAD

**Issue by javiermarcon** [timhughes/django-cbv-inline-formset#4]
Hello, thanks for making this project. When I try to make the migrations to use it, I get this error:
TypeError: __init__() missing 1 required positional argument: 'on_delete'
Do you have any idea on what can be causing it?
Thanks.

**Comment by javiermarcon** [comment]
This error is solved changing the model class:

class Track(models.Model):
    album = models.ForeignKey('Album', on_delete=models.CASCADE)
    number = models.IntegerField()
    name = models.CharField(max_length=100)

**Comment by timhughes** [comment]
Cheers, thanks
Updated https://github.com/timhughes/django-cbv-inline-formset/commit/272fd7c1f96c8608413e7442624eab187c2f488a
