### ISSUE TITLE
my inlineformset only save the last form

### ISSUE THREAD

**Issue by jordan-bys** [timhughes/django-cbv-inline-formset#5]
i have a problem with my inlineformset please can you help me ?
https://stackoverflow.com/questions/62252867/inline-formset-only-save-the-last-form
i appreciate your helps

**Comment by timhughes** [comment]
https://stackoverflow.com/questions/62252867/inline-formset-only-save-the-last-form/62259041#62259041  Done my best :-)

**Comment by jordan-bys** [comment]
thank you for your reply , it didnt work
